spring.application.name=OrderService

server.port=8084

# 'postgres' = container_name in docker-compose, Docker DNS resolves it automatically
#spring.datasource.url=jdbc:postgresql://postgres:5432/EcomOrder
spring.datasource.url=jdbc:postgresql://localhost:5432/EcomOrder
spring.datasource.username=postgres
spring.datasource.password=Ashu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 'eureka-server' = service name in docker-compose
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/