spring.application.name=CartService

server.port=8083

# 'postgres' = container_name in docker-compose, Docker DNS resolves it automatically
#spring.datasource.url=jdbc:postgresql://postgres:5432/EcomCart
spring.datasource.url=jdbc:postgresql://localhost:5432/EcomCart
spring.datasource.username=postgres
spring.datasource.password=Ashu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 'eureka-server' = service name in docker-compose
#eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/